name: MSBuild
on: [push, pull_request]
jobs:
  build:
    name: MSBuild
    # runs-on: self-hosted
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v1
      with:
        fetch-depth: 1

    # - name: Setup MSBuild.exe
    #   uses: warrenbuckley/Setup-MSBuild@v1
    - name: Add path
      run: set PATH=%PATH%;C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\MSBuild\Current\Bin
      shell: cmd

    - name: MSBuild
      run: msbuild msbuild_actions_sample.sln -p:OutDir="out"
      shell: cmd

    - name: Upload artifact
      uses: actions/upload-artifact@v1
      with:
        name: build-result
        path: ./msbuild_actions_sample/out/

